export const ERROR_CODE_DICTIONARY = {
  ALREADY_FROZEN: "User account is already frozen.",
  DEVICE_NOT_FOUND: "Requested device does not exist.",
  DEVICE_REVOKE_BLOCKED: "Current device cannot be revoked.",
  DISPUTE_NOT_FOUND: "Dispute was not found.",
  EVENT_NOT_FOUND: "Event was not found.",
  EVENT_TICKET_TYPE_MISMATCH: "Ticket type does not belong to the provided event.",
  FORBIDDEN: "Caller is not allowed to perform this action.",
  INSUFFICIENT_INVENTORY: "Not enough inventory is available.",
  INTERNAL_ERROR: "Internal server error.",
  INVALID_CHECKIN_PAYLOAD: "Check-in request payload is invalid.",
  INVALID_CURRENCY: "Currency is invalid for this operation.",
  INVALID_DISPUTE_PAYLOAD: "Dispute payload is invalid.",
  INVALID_EMAIL: "Email payload is invalid.",
  INVALID_EVENT_PAYLOAD: "Event payload is invalid.",
  INVALID_FACE_MATCH_PAYLOAD: "Face-match payload is invalid.",
  INVALID_JSON: "Request body must be valid JSON.",
  INVALID_KYC_UPLOAD: "KYC upload payload is invalid.",
  INVALID_LISTING_PAYLOAD: "Listing payload is invalid.",
  INVALID_MESSAGE: "Message payload is invalid.",
  INVALID_MINT_JOB_PAYLOAD: "Mint job payload is invalid.",
  INVALID_MODERATION_PAYLOAD: "Moderation payload is invalid.",
  INVALID_NOTIFICATION_PAYLOAD: "Notification payload is invalid.",
  INVALID_ORIGINAL_PRICE: "Original ticket price is invalid.",
  INVALID_PAYMENT_INTENT_PAYLOAD: "Payment intent payload is invalid.",
  INVALID_PHONE: "Phone number is invalid.",
  INVALID_PRICE: "Price is invalid.",
  INVALID_PROVIDER_STATUS_PAYLOAD: "Provider status payload is invalid.",
  INVALID_PURCHASE_PAYLOAD: "Purchase payload is invalid.",
  INVALID_QR_PAYLOAD: "QR payload is invalid.",
  INVALID_QUANTITY: "Quantity value is invalid.",
  INVALID_RECOVERY_PAYLOAD: "Recovery payload is invalid.",
  INVALID_RECOVERY_STATE: "Recovery state does not allow this action.",
  INVALID_REFRESH_PAYLOAD: "Refresh payload is invalid.",
  INVALID_REFUND_PAYLOAD: "Refund payload is invalid.",
  INVALID_RESERVATION_PAYLOAD: "Reservation payload is invalid.",
  INVALID_SETTLEMENT_PAYLOAD: "Settlement payload is invalid.",
  INVALID_SETTLEMENT_SPLIT: "Settlement split values are invalid.",
  INVALID_SPLIT: "Fee split values are invalid.",
  INVALID_VERIFY_PAYLOAD: "Verification payload is invalid.",
  INVALID_WEBHOOK_PAYLOAD: "Webhook payload is invalid.",
  KYC_PROVIDER_UNAVAILABLE: "KYC provider is unavailable.",
  KYC_REQUIRED: "KYC is required for this operation.",
  LISTING_ALREADY_ACTIVE: "Listing is already active.",
  LISTING_MISMATCH: "Listing does not match target asset.",
  LISTING_NOT_ACTIVE: "Listing is not active.",
  LISTING_NOT_FOUND: "Listing was not found.",
  MARKUP_EXCEEDED: "Listing price exceeds allowed markup.",
  MAX_TIER_REACHED: "Dispute already at max escalation tier.",
  MINT_JOB_NOT_FOUND: "Mint job was not found.",
  MISSING_GUARDIAN_ADDRESS: "Guardian address is required.",
  NOT_FOUND: "Route not found.",
  NOT_FROZEN: "User account is not frozen.",
  OTP_EXPIRED: "OTP is expired.",
  OTP_INVALID: "OTP is invalid.",
  OTP_NOT_FOUND: "OTP session was not found.",
  OTP_RATE_LIMITED: "OTP request was rate-limited.",
  PAYMENT_NOT_CONFIRMED: "Payment status is not confirmed.",
  PAYMENT_NOT_FOUND: "Payment was not found.",
  RECOVERY_ALREADY_ACTIVE: "Recovery request already exists.",
  RECOVERY_HOLD_NOT_FINISHED: "Recovery hold period has not finished.",
  RECOVERY_NOT_FOUND: "Recovery request was not found.",
  REFRESH_INVALID: "Refresh token is invalid.",
  REFUND_ALREADY_REQUESTED: "Refund has already been requested.",
  REFUND_NOT_FOUND: "Refund was not found.",
  RESERVATION_EXPIRED: "Reservation has expired.",
  RESERVATION_NOT_FOUND: "Reservation was not found.",
  RESERVATION_NOT_PENDING: "Reservation is not pending.",
  RESERVATION_NOT_PENDING_PAYMENT: "Reservation is not pending payment confirmation.",
  SELF_PURCHASE_FORBIDDEN: "User cannot purchase their own listing.",
  SESSION_NOT_FOUND: "Session was not found.",
  SESSION_REVOKED: "Session has already been revoked.",
  TEMPLATE_NOT_FOUND: "Notification template was not found.",
  TICKET_NOT_FOUND: "Ticket was not found.",
  UNAUTHORIZED: "Authentication is required.",
  UNAUTHORIZED_INTERNAL: "Internal authentication failed.",
  UNAUTHORIZED_ORGANIZER: "Organizer authentication is required.",
  UNKNOWN_TICKET_TYPE: "Ticket type is not supported.",
  UNSUPPORTED_CURRENCY: "Currency is not supported.",
  UNSUPPORTED_GATEWAY: "Gateway is not supported.",
  UNSUPPORTED_MODERATION_ACTION: "Moderation action is not supported.",
  UPSTREAM_UNAVAILABLE: "Upstream service is unavailable.",
  WEBHOOK_INVALID_TIMESTAMP: "Webhook timestamp is invalid.",
  WEBHOOK_REPLAY_DETECTED: "Webhook replay detected.",
  WEBHOOK_SIGNATURE_HEADERS_MISSING: "Required webhook signature headers are missing.",
  WEBHOOK_SIGNATURE_INVALID: "Webhook signature is invalid.",
  WEBHOOK_TIMESTAMP_OUT_OF_RANGE: "Webhook timestamp is outside allowed range."
} as const;

export type ApiErrorCode = keyof typeof ERROR_CODE_DICTIONARY;

export interface ApiErrorPayload {
  code: ApiErrorCode;
  message: string;
}

export interface ApiErrorResponse {
  success: false;
  error: ApiErrorPayload;
}
