#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="$ROOT_DIR/.tmp/localchain"
PID_FILE="$STATE_DIR/anvil.pid"
LOG_FILE="$STATE_DIR/anvil.log"
DEPLOYMENT_FILE="$ROOT_DIR/contracts/deployments/localchain-addresses.json"
ENV_FILE="$ROOT_DIR/.env.localchain"

DEFAULT_ANVIL_HOST="127.0.0.1"
DEFAULT_ANVIL_PORT="8545"
DEFAULT_CHAIN_ID="31337"
DEFAULT_PUBLIC_HOST="127.0.0.1"
DEFAULT_PRIVATE_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
DEFAULT_MNEMONIC="test test test test test test test test test test test junk"
DEFAULT_DEMO_USER_ID="buyer_demo_web_3"
DEFAULT_DEMO_WALLET_ADDRESS="0x90F79bf6EB2c4f870365E785982E1f101E93b906"

mkdir -p "$STATE_DIR"

ensure_tools() {
  command -v anvil >/dev/null 2>&1 || {
    echo "Missing required tool: anvil"
    exit 1
  }
  command -v forge >/dev/null 2>&1 || {
    echo "Missing required tool: forge"
    exit 1
  }
  command -v cast >/dev/null 2>&1 || {
    echo "Missing required tool: cast"
    exit 1
  }
  command -v node >/dev/null 2>&1 || {
    echo "Missing required tool: node"
    exit 1
  }
}

read_env_file() {
  local override_host_is_set="${HOST+x}"
  local override_host="${HOST:-}"
  local override_anvil_host_is_set="${ANVIL_HOST+x}"
  local override_anvil_host="${ANVIL_HOST:-}"
  local override_rpc_url_is_set="${RPC_URL+x}"
  local override_rpc_url="${RPC_URL:-}"
  local override_public_host_is_set="${LOCALCHAIN_PUBLIC_HOST+x}"
  local override_public_host="${LOCALCHAIN_PUBLIC_HOST:-}"
  local override_vite_api_base_url_is_set="${VITE_API_BASE_URL+x}"
  local override_vite_api_base_url="${VITE_API_BASE_URL:-}"
  local override_vite_rpc_url_is_set="${VITE_RPC_URL+x}"
  local override_vite_rpc_url="${VITE_RPC_URL:-}"

  if [[ -f "$ENV_FILE" ]]; then
    set -a
    source "$ENV_FILE"
    set +a
  fi

  [[ -n "$override_host_is_set" ]] && HOST="$override_host"
  [[ -n "$override_anvil_host_is_set" ]] && ANVIL_HOST="$override_anvil_host"
  [[ -n "$override_rpc_url_is_set" ]] && RPC_URL="$override_rpc_url"
  [[ -n "$override_public_host_is_set" ]] && LOCALCHAIN_PUBLIC_HOST="$override_public_host"
  [[ -n "$override_vite_api_base_url_is_set" ]] && VITE_API_BASE_URL="$override_vite_api_base_url"
  [[ -n "$override_vite_rpc_url_is_set" ]] && VITE_RPC_URL="$override_vite_rpc_url"
  return 0
}

anvil_host() {
  printf '%s' "${ANVIL_HOST:-$DEFAULT_ANVIL_HOST}"
}

anvil_port() {
  printf '%s' "${ANVIL_PORT:-$DEFAULT_ANVIL_PORT}"
}

chain_id() {
  printf '%s' "${CHAIN_ID:-$DEFAULT_CHAIN_ID}"
}

rpc_connect_host() {
  local host
  host="$(anvil_host)"
  if [[ "$host" == "0.0.0.0" || "$host" == "::" ]]; then
    printf '%s' "$DEFAULT_ANVIL_HOST"
  else
    printf '%s' "$host"
  fi
}

rpc_url() {
  printf '%s' "${RPC_URL:-http://$(rpc_connect_host):$(anvil_port)}"
}

private_key() {
  printf '%s' "${PRIVATE_KEY:-$DEFAULT_PRIVATE_KEY}"
}

public_host() {
  printf '%s' "${LOCALCHAIN_PUBLIC_HOST:-$DEFAULT_PUBLIC_HOST}"
}

frontend_api_base_url() {
  printf 'http://%s:3000' "$(public_host)"
}

frontend_rpc_url() {
  printf 'http://%s:%s' "$(public_host)" "$(anvil_port)"
}

is_running() {
  local pid="$1"
  kill -0 "$pid" >/dev/null 2>&1
}

wait_for_rpc() {
  local url="$1"
  for _ in $(seq 1 30); do
    if curl -fsS \
      -H "content-type: application/json" \
      -d '{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}' \
      "$url" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done

  echo "Anvil RPC did not become ready at $url"
  return 1
}

write_env_file() {
  local deploy_admin="$1"
  local ticket_ledger_address="$2"
  local marketplace_address="$3"
  local paymaster_address="$4"
  local handler_address="$5"

  cat >"$ENV_FILE" <<EOF
# Local-chain runtime for Ticket Platform monorepo.
# Generated by scripts/localchain.sh. Re-run \`npm run chain:up\` or
# \`npm run chain:deploy\` after resetting Anvil.

# Shared host binding
HOST=${HOST:-127.0.0.1}

# UI simulator
UI_HOST=127.0.0.1
UI_PORT=4310
UI_SKIP_BUILD=0

# Internal service auth
INTERNAL_API_KEY=internal-dev-key

# API gateway
REQUEST_TIMEOUT_MS=2000
AUTH_SERVICE_BASE_URL=http://127.0.0.1:3001
USER_SERVICE_BASE_URL=http://127.0.0.1:3002
KYC_SERVICE_BASE_URL=http://127.0.0.1:3003
EVENT_SERVICE_BASE_URL=http://127.0.0.1:3004
TICKETING_SERVICE_BASE_URL=http://127.0.0.1:3005
PAYMENT_ORCHESTRATOR_BASE_URL=http://127.0.0.1:3006
MARKETPLACE_SERVICE_BASE_URL=http://127.0.0.1:3007
CHECKIN_SERVICE_BASE_URL=http://127.0.0.1:3008
REFUND_SERVICE_BASE_URL=http://127.0.0.1:3009
RECOVERY_SERVICE_BASE_URL=http://127.0.0.1:3011
DISPUTE_SERVICE_BASE_URL=http://127.0.0.1:3012
NOTIFICATION_SERVICE_BASE_URL=http://127.0.0.1:3013
CONTRACT_SYNC_SERVICE_BASE_URL=http://127.0.0.1:3014

# Auth service
OTP_LENGTH=6
OTP_TTL_SEC=300
OTP_MAX_REQUESTS_PER_WINDOW=5
OTP_RATE_WINDOW_SEC=900
ACCESS_TOKEN_TTL_SEC=900
REFRESH_TOKEN_TTL_SEC=2592000
AUTH_EXPOSE_OTP_IN_RESPONSE=true

# KYC service
KYC_PROVIDER=fpt
KYC_FALLBACK_PROVIDER=vnpt
KYC_MIN_LIVENESS_SCORE=0.8
KYC_MIN_FACE_MATCH_SCORE=0.7

# Ticketing service
RESERVATION_TTL_SEC=900

# Payment orchestrator
ALLOWED_PAYMENT_GATEWAYS=momo,vnpay
MOMO_WEBHOOK_SECRET=momo_dev_secret
VNPAY_WEBHOOK_SECRET=vnpay_dev_secret
WEBHOOK_MAX_SKEW_SEC=300
WEBHOOK_NONCE_TTL_SEC=1800
MAX_WEBHOOK_RETRIES=5
RETRY_BASE_DELAY_SEC=30
BACKEND_SIGNER_PRIVATE_KEY=$(private_key)
TICKET_LEDGER_CHAIN_ID=$(chain_id)
TICKET_LEDGER_ADDRESS=$ticket_ledger_address
PAYMENT_HASH_TTL_SEC=86400
WALLET_PREFUND_AMOUNT_WEI=1000000000000000
CAST_BINARY_PATH=cast

# Marketplace service
MAX_MARKUP_BPS=12000
PLATFORM_FEE_BPS=500
ORGANIZER_ROYALTY_BPS=200
MARKETPLACE_CHAIN_ID=$(chain_id)
MARKETPLACE_ADDRESS=$marketplace_address
BUY_HASH_TTL_SEC=86400

# Check-in service
QR_SIGNATURE_SECRET=checkin_dev_secret
MAX_QR_AGE_SEC=30
MAX_CLOCK_SKEW_SEC=10
MARK_AS_USED_POLL_MS=1000
MARK_AS_USED_MAX_RETRIES=3
MARK_AS_USED_FAILURE_RATE=0

# Refund service
PAYOUT_SYNC_POLL_MS=2000
MAX_REFUND_RETRY_COUNT=3
REFUND_RETRY_BASE_DELAY_SEC=30
PAYOUT_FAILURE_RATE=0

# Recovery service
RECOVERY_HOLD_DURATION_SEC=172800
REQUIRED_VERIFICATION_CHANNELS=2
ELIGIBILITY_SCAN_INTERVAL_MS=1000

# Dispute service
SLA_TIER1_HOURS=24
SLA_TIER2_HOURS=48
SLA_TIER3_HOURS=72

# Notification service
DELIVERY_POLL_MS=1000
MAX_NOTIFICATION_RETRIES=2
DELIVERY_FAILURE_RATE=0

# Worker mint
MAX_MINT_ATTEMPTS=5
MAX_MINT_BATCH_SIZE=10
TOKEN_ID_SEED=100000

# Contract sync / local chain
CHAIN_ID=$(chain_id)
RPC_URL=$(rpc_url)
PRIVATE_KEY=$(private_key)
DEPLOY_ADMIN=$deploy_admin
TICKET_LEDGER_ADDRESS=$ticket_ledger_address
MARKETPLACE_ADDRESS=$marketplace_address
PAYMASTER_ADDRESS=$paymaster_address
HANDLER_ADDRESS=$handler_address
TICKET_NFT_ADDRESS=$ticket_ledger_address

# Frontend
VITE_API_BASE_URL=$(frontend_api_base_url)
VITE_RPC_URL=$(frontend_rpc_url)
VITE_DEMO_USER_ID=$DEFAULT_DEMO_USER_ID
VITE_DEMO_WALLET_ADDRESS=$DEFAULT_DEMO_WALLET_ADDRESS
VITE_HANDLER_ADDRESS=$handler_address
VITE_DEMO_MOMO_WEBHOOK_SECRET=momo_dev_secret

# Docker Compose local infra
COMPOSE_PROJECT_NAME=ticket-platform-local
POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=5432
POSTGRES_DB=ticket_platform
POSTGRES_USER=ticket_platform
POSTGRES_PASSWORD=ticket_platform
DATABASE_URL=postgresql://ticket_platform:ticket_platform@127.0.0.1:5432/ticket_platform
POSTGRES_POOL_MAX=10
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_URL=redis://127.0.0.1:6379
MINIO_API_PORT=9000
MINIO_CONSOLE_PORT=9001
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin
MINIO_ENDPOINT=http://127.0.0.1:9000
MINIO_REGION=us-east-1
MINIO_FORCE_PATH_STYLE=true
KYC_ARCHIVE_BUCKET=ticket-platform-kyc-local

# Anvil launcher settings
ANVIL_HOST=$(anvil_host)
ANVIL_PORT=$(anvil_port)
ANVIL_CHAIN_ID=$(chain_id)
ANVIL_MNEMONIC="$DEFAULT_MNEMONIC"
EOF
}

create_placeholder_env() {
  write_env_file \
    "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266" \
    "0x0000000000000000000000000000000000000000" \
    "0x0000000000000000000000000000000000000000" \
    "0x0000000000000000000000000000000000000000" \
    "0x0000000000000000000000000000000000000000"
}

start_chain() {
  ensure_tools
  read_env_file

  if [[ -f "$PID_FILE" ]]; then
    local existing_pid
    existing_pid="$(cat "$PID_FILE")"
    if is_running "$existing_pid"; then
      echo "Anvil already running (pid $existing_pid)"
      wait_for_rpc "$(rpc_url)"
      return 0
    fi
    rm -f "$PID_FILE"
  fi

  nohup anvil \
    --host "$(anvil_host)" \
    --port "$(anvil_port)" \
    --chain-id "$(chain_id)" \
    --allow-origin "*" \
    --mnemonic "$DEFAULT_MNEMONIC" \
    >"$LOG_FILE" 2>&1 &
  echo $! >"$PID_FILE"

  wait_for_rpc "$(rpc_url)"
  echo "Anvil ready at $(rpc_url)"
}

stop_chain() {
  if [[ ! -f "$PID_FILE" ]]; then
    echo "Anvil is not running"
    return 0
  fi

  local pid
  pid="$(cat "$PID_FILE")"
  if is_running "$pid"; then
    kill "$pid" >/dev/null 2>&1 || true
    for _ in $(seq 1 10); do
      if ! is_running "$pid"; then
        break
      fi
      sleep 1
    done
    if is_running "$pid"; then
      kill -9 "$pid" >/dev/null 2>&1 || true
    fi
    echo "Stopped Anvil (pid $pid)"
  fi

  rm -f "$PID_FILE"
}

deploy_contracts() {
  ensure_tools
  if [[ ! -f "$ENV_FILE" ]]; then
    create_placeholder_env
  fi
  read_env_file
  start_chain

  local deploy_admin
  deploy_admin="${DEPLOY_ADMIN:-$(cast wallet address --private-key "$(private_key)")}"

  (
    cd "$ROOT_DIR/contracts"
    DEPLOY_ADMIN="$deploy_admin" \
    DEPLOY_OUTPUT_PATH="$DEPLOYMENT_FILE" \
    forge script script/DeployLocalPlatform.s.sol:DeployLocalPlatform \
      --rpc-url "$(rpc_url)" \
      --private-key "$(private_key)" \
      --broadcast
  )

  eval "$(
    node -e '
      const fs = require("fs");
      const file = process.argv[1];
      const deployment = JSON.parse(fs.readFileSync(file, "utf8"));
      console.log(`TICKET_LEDGER_ADDRESS=${deployment.ticketLedger}`);
      console.log(`MARKETPLACE_ADDRESS=${deployment.marketplaceV2}`);
      console.log(`PAYMASTER_ADDRESS=${deployment.ticketPaymaster}`);
      console.log(`HANDLER_ADDRESS=${deployment.handler}`);
      console.log(`DEPLOY_ADMIN=${deployment.deployAdmin}`);
    ' "$DEPLOYMENT_FILE"
  )"

  write_env_file \
    "$DEPLOY_ADMIN" \
    "$TICKET_LEDGER_ADDRESS" \
    "$MARKETPLACE_ADDRESS" \
    "$PAYMASTER_ADDRESS" \
    "$HANDLER_ADDRESS"

  echo "Contracts deployed:"
  echo "- TicketLedger:    $TICKET_LEDGER_ADDRESS"
  echo "- MarketplaceV2:  $MARKETPLACE_ADDRESS"
  echo "- TicketPaymaster:$PAYMASTER_ADDRESS"
  echo "- Handler:         $HANDLER_ADDRESS"
  echo "- Env file:        $ENV_FILE"
}

status() {
  if [[ -f "$PID_FILE" ]]; then
    local pid
    pid="$(cat "$PID_FILE")"
    if is_running "$pid"; then
      echo "Anvil: RUNNING pid=$pid rpc=$(rpc_url)"
    else
      echo "Anvil: STOPPED (stale pid file)"
      rm -f "$PID_FILE"
    fi
  else
    echo "Anvil: STOPPED"
  fi

  if [[ -f "$DEPLOYMENT_FILE" ]]; then
    echo "Deployment: $DEPLOYMENT_FILE"
    node -e '
      const fs = require("fs");
      const deployment = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
      console.log(`- chainId:        ${deployment.chainId}`);
      console.log(`- deployAdmin:    ${deployment.deployAdmin}`);
      console.log(`- ticketLedger:   ${deployment.ticketLedger}`);
      console.log(`- marketplaceV2:  ${deployment.marketplaceV2}`);
      console.log(`- ticketPaymaster:${deployment.ticketPaymaster}`);
      console.log(`- handler:        ${deployment.handler}`);
    ' "$DEPLOYMENT_FILE"
  fi

  if [[ -f "$ENV_FILE" ]]; then
    echo "Env: $ENV_FILE"
  fi
}

run_web() {
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "Missing $ENV_FILE. Run 'npm run chain:up' first."
    exit 1
  fi

  read_env_file
  PATH="$ROOT_DIR/bin:$PATH" pnpm --filter @ticket-platform/app-web dev
}

full_up() {
  deploy_contracts
  STACK_ENV_FILE=.env.localchain "$ROOT_DIR/scripts/dev-stack.sh" up
  "$ROOT_DIR/scripts/localchain-smoke.sh"
}

full_down() {
  STACK_ENV_FILE=.env.localchain "$ROOT_DIR/scripts/dev-stack.sh" down || true
  stop_chain
}

case "${1:-up}" in
  up)
    deploy_contracts
    ;;
  deploy)
    deploy_contracts
    ;;
  down)
    stop_chain
    ;;
  status)
    status
    ;;
  full-up)
    full_up
    ;;
  full-down)
    full_down
    ;;
  web)
    run_web
    ;;
  *)
    echo "Usage: $0 {up|deploy|down|status|full-up|full-down|web}"
    exit 1
    ;;
esac
